import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication } from '@nestjs/common';
import * as request from 'supertest';
import { AppModule } from '../src/app.module';
import { EmailService } from '../src/modules/email/email.service';
import { ConfigService } from '@nestjs/config';

describe('Email Integration Tests', () => {
  let app: INestApplication;
  let emailService: EmailService;
  let configService: ConfigService;

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    emailService = moduleFixture.get<EmailService>(EmailService);
    configService = moduleFixture.get<ConfigService>(ConfigService);

    await app.init();
  });

  afterAll(async () => {
    await app.close();
  });

  describe('Email Service Integration', () => {
    it('should send verification email in real environment', async () => {
      // Skip if email is not configured
      const emailEnabled = configService.get('email.enabled');
      if (!emailEnabled) {
        console.log('Skipping email integration test - email not enabled');
        return;
      }

      const email = 'integration-test@example.com';
      const token = 'test-jwt-token';
      const userName = 'Integration Test User';

      // Use a test token that would be generated by the auth service
      const jwtToken = configService.get('jwt.secret') 
        ? require('jsonwebtoken').sign(
            { sub: 1, email, type: 'email_verification' },
            configService.get('jwt.secret'),
            { expiresIn: '24h' }
          )
        : 'mock-jwt-token';

      const result = await emailService.sendVerificationEmail(email, jwtToken, userName);

      // In a real environment, this would send an actual email
      // For integration testing, we just verify the service doesn't crash
      expect(typeof result).toBe('boolean');
    });

    it('should send password reset email in real environment', async () => {
      const emailEnabled = configService.get('email.enabled');
      if (!emailEnabled) {
        console.log('Skipping email integration test - email not enabled');
        return;
      }

      const email = 'integration-test-reset@example.com';
      const token = 'test-reset-token';
      const userName = 'Integration Test User';

      const jwtToken = configService.get('jwt.secret')
        ? require('jsonwebtoken').sign(
            { sub: 1, email, type: 'password_reset' },
            configService.get('jwt.secret'),
            { expiresIn: '1h' }
          )
        : 'mock-jwt-token';

      const result = await emailService.sendPasswordResetEmail(email, jwtToken, userName);

      expect(typeof result).toBe('boolean');
    });

    it('should send welcome email in real environment', async () => {
      const emailEnabled = configService.get('email.enabled');
      if (!emailEnabled) {
        console.log('Skipping email integration test - email not enabled');
        return;
      }

      const email = 'integration-test-welcome@example.com';
      const userName = 'Integration Test User';

      const result = await emailService.sendWelcomeEmail(email, userName);

      expect(typeof result).toBe('boolean');
    });

    it('should handle template rendering integration', async () => {
      const emailEnabled = configService.get('email.enabled');
      if (!emailEnabled) {
        console.log('Skipping email integration test - email not enabled');
        return;
      }

      const email = 'integration-test-template@example.com';
      const template = 'verify-email';
      const context = {
        userName: 'Template Test User',
        verificationUrl: 'http://localhost:4200/verify?token=test-token',
        token: 'test-token-123',
        expiresIn: '24 hours',
      };

      const result = await emailService.sendGenericEmail(
        email,
        'Template Test Subject',
        template,
        context
      );

      expect(typeof result).toBe('boolean');
    });

    it('should handle email configuration validation', async () => {
      const emailEnabled = configService.get('email.enabled');
      
      // Test that the service can be initialized even without email configuration
      expect(emailService).toBeDefined();
      
      if (emailEnabled) {
        console.log('Email is enabled - configuration is valid');
      } else {
        console.log('Email is disabled - this is expected for some environments');
      }
    });

    it('should handle frontend URL configuration', async () => {
      const frontendUrl = configService.get('email.frontendUrl');
      expect(frontendUrl).toBeDefined();
      expect(typeof frontendUrl).toBe('string');
      
      // Verify URL format
      expect(frontendUrl).toMatch(/^https?:\/\/.+$/);
    });

    it('should handle email configuration validation', async () => {
      const emailConfig = {
        enabled: configService.get('email.enabled'),
        provider: configService.get('email.provider'),
        from: configService.get('email.defaults.from'),
      };

      expect(emailConfig).toBeDefined();
      expect(typeof emailConfig.enabled).toBe('boolean');
      expect(typeof emailConfig.provider).toBe('string');
      expect(typeof emailConfig.from).toBe('string');
    });
  });

  describe('Email Configuration Tests', () => {
    it('should validate email environment variables', () => {
      const requiredVars = [
        'email.enabled',
        'email.provider',
        'email.defaults.from',
      ];

      requiredVars.forEach(varName => {
        const value = configService.get(varName);
        expect(value).toBeDefined();
        console.log(`${varName}: ${value}`);
      });
    });

    it('should handle missing optional environment variables gracefully', () => {
      const optionalVars = [
        'email.host',
        'email.port',
        'email.secure',
        'email.user',
        'email.password',
      ];

      optionalVars.forEach(varName => {
        const value = configService.get(varName);
        // Optional vars can be undefined
        expect(value === undefined || typeof value === 'string').toBe(true);
      });
    });
  });

  describe('Error Handling Integration', () => {
    it('should handle invalid email addresses gracefully', async () => {
      const invalidEmails = [
        'invalid-email',
        '@example.com',
        'user@',
        '',
        'user@domain',
      ];

      for (const email of invalidEmails) {
        try {
          const result = await emailService.sendGenericEmail(
            email,
            'Test Subject',
            'verify-email',
            { userName: 'Test User' }
          );
          // Service should handle invalid emails gracefully
          expect(typeof result).toBe('boolean');
        } catch (error) {
          // If an error is thrown, it should be handled gracefully
          expect(error).toBeDefined();
        }
      }
    });

    it('should handle template rendering errors', async () => {
      const result = await emailService.sendGenericEmail(
        'test@example.com',
        'Test Subject',
        'non-existent-template',
        { context: 'test' }
      );
      
      // Should return false for template rendering errors
      expect(typeof result).toBe('boolean');
    });
  });

  describe('Performance Tests', () => {
    it('should handle concurrent email sending', async () => {
      const emailEnabled = configService.get('email.enabled');
      if (!emailEnabled) {
        console.log('Skipping performance test - email not enabled');
        return;
      }

      const concurrentEmails = 5;
      const promises = [];

      for (let i = 0; i < concurrentEmails; i++) {
        const email = `concurrent-test-${i}@example.com`;
        const promise = emailService.sendGenericEmail(
          email,
          `Concurrent Test ${i}`,
          'verify-email',
          { userName: `User ${i}`, verificationUrl: 'http://localhost:4200/test' }
        );
        promises.push(promise);
      }

      const results = await Promise.all(promises);
      expect(results).toHaveLength(concurrentEmails);
      results.forEach(result => {
        expect(typeof result).toBe('boolean');
      });
    }, 30000); // 30 second timeout for performance test
  });
});
